#!/usr/bin/env ruby
# frozen_string_literal: true

require 'odin/mastermind'

config = Odin::Mastermind::Configuration.new(code_length: 4, value_range: 0..5, max_turns: 12)
game_io = Odin::Mastermind::CommandLineIO.new(stdout: $stdout, stdin: $stdin, config:)
code_maker = Odin::Mastermind::ComputerPlayer.new(name: 'Computer', config:)
code_breaker = Odin::Mastermind::HumanPlayer.new(name: 'Human', config:, game_io:)
game_engine = Odin::Mastermind::GameEngine.new(code_maker:, code_breaker:, config:, game_io:)

game_engine.run
